version: 0.0
os: linux

files:
  - source:  /
    destination: /home/ubuntu/var/www/BOB_Server
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

#hooks:
#  AfterInstall:
#    - location: stop.sh
#      timeout: 60
#      runas: ubuntu
#  ApplicationStart:
#    - location: start.sh
#      timeout: 60
#      runas: ubuntu

